config/routes.rb
Rails.application.routes.draw do

  # Root Homepage
  root                  to: 'public/pages#home'
  get '/:locale',       to: 'public/pages#home'

  # Local routes
  scope '/:locale' do

    resources :errors, only: [:show]

    namespace :admin do
      resources :users, :countries, :entries, :categories

      resources :courses do
        resources :lessons
      end

      # Attachments resource
      match '/attachments/:model/:id/:attachment/:return_url/(.:format)' => 'attachments#destroy', as: :attachment, via: [:delete, :get, :post]
    end

    scope module: 'public' do

      # Search resource aliases
      get     'search',                       to: 'searches#show'

      # Pages resource aliases
      get     '',                             to: 'pages#show', id: 'home'

      # Sessions resource aliases
      get     'login',                        to: 'sessions#new'
      post    'login',                        to: 'sessions#create'
      get     'logout',                       to: 'sessions#destroy'

      # User resource aliases
      get     'user/register',                to: 'users#new'
      post    'user/register',                to: 'users#create'
      get     'user/registered/:token',       to: 'users#created'
      get     'user/activate/:token',         to: 'users#activate'
      get     'user/activated/:token',        to: 'users#activated'
      get     'user/edit',                    to: 'users#edit'
      patch   'user/edit',                    to: 'users#update'
      get     'user/delete',                  to: 'users#delete'
      patch   'user/delete',                  to: 'users#activate_removal'
      get     'user/remove/:token',           to: 'users#destroy'
      get     'user/removed/:token',          to: 'users#removed'

      # Contact messages
      get     'contact',                      to: 'contact_messages#new'
      post    'contact',                      to: 'contact_messages#create'

      # Email change aliases
      get     'user/email-change',            to: 'email_changes#new'
      post    'user/email-change',            to: 'email_changes#create'
      get     'user/email-change/:token',     to: 'email_changes#update'

      # Password change aliases
      get     'user/password-change',         to: 'password_changes#edit'
      put     'user/password-change',         to: 'password_changes#update'

      # Password reset aliases
      get     'user/password-reset',          to: 'password_resets#new'
      post    'user/password-reset',          to: 'password_resets#create'
      get     'user/password-reset/:token',   to: 'password_resets#edit'
      put     'user/password-reset/:token',   to: 'password_resets#update'

      # Users resource
      resources :users do
        member do
          get 'created'             # Information page that activation email was sent.
          get 'activate'            # Activate user account.
          get 'activated'           # Welcome page for activated user.
          get 'delete'              # Form to remove account.
          patch 'activate_removal'  # Sent an email message with confirmation link for removal process.
          get 'removed'             # Message that account had been removed.
        end

        # Password Change resource
        resource :password_change,  only: [:edit, :update]

        # Email Change resource
        resource :email_change,  only: [:new, :create, :update]
      end

      # Password reset resource
      resources :password_resets, only: [:new, :create, :edit, :update] do
        collection do
          get 'created'
        end
      end

      # Pages resource
      resources :pages, only: [:show]

      # Contact messages resource
      resources :contact_messages,     only: [:new, :create]

      # Entries resource
      resources :entries,     only: [:show]

      # Categories resource
      # resources :categories,  only: [ :show ]

      # Search resource
      resource :searches,    only: [:show]

      # Sessions resource
      resource  :sessions,    only: [:new, :create, :destroy]

      # Dashboard resource
      resource  :dashboard,   only: [:show]

    end

  end

  # mount Ckeditor::Engine => '/ckeditor'
end

app/models/base_model/country.rb
class BaseModel::Country < ActiveRecord::Base
  self.table_name = 'country'

  has_many :entries

  as_enum :payment_provider_type, { dot_pay: 'DotPay' }, source: 'payment_provider'

  validates :name,              presence:     true,
                                length:       4..32
  validates :currency_code,     presence:     true,
                                length:       { is: 3 }
  validates :code,              presence:     true,
                                length:       { is: 2 }
  validates :currency_symbol,   presence:     true,
                                length:       1..32
  validates :payment_provider,  presence:     true
  validates :tax,               presence:     true,
                                numericality: { greater_than_or_equal_to: 0.00, less_than_or_equal_to: 100.00 }
  validates :language,          presence:     true,
                                length:       { is: 2 }

  after_initialize :init

  def init
    self.tax = 0
  end
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < Admin::AdminController
  helper_method :sort_column, :sort_direction

  # GET /admin/countries
  # GET /admin/countries.json
  def index
    @countries = BaseModel::Country.paginate(:page => params[:page]).order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @countries }
    end
  end

  # GET /admin/countries/1
  # GET /admin/countries/1.json
  def show
    @country = BaseModel::Country.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @country }
    end
  end

  # GET /admin/countries/new
  # GET /admin/countries/new.json
  def new
    @country = BaseModel::Country.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @country }
    end
  end

  # GET /admin/countries/1/edit
  def edit
    @country = BaseModel::Country.find(params[:id])
  end

  # POST /admin/countries
  # POST /admin/countries.json
  def create
    @country = BaseModel::Country.new(params[:admin_country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to :action => "index", notice: 'Country was successfully created.' }
        format.json { render json: @country, status: :created, location: @country }
      else
        format.html { render action: "new" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/countries/1
  # PUT /admin/countries/1.json
  def update
    @country = BaseModel::Country.find(params[:id])

    respond_to do |format|
      if @country.update_attributes(params[:admin_country])
        format.html { redirect_to :action => "index", notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/countries/1
  # DELETE /admin/countries/1.json
  def destroy
    @country = BaseModel::Country.find(params[:id])
    @country.destroy

    respond_to do |format|
      format.html { redirect_to admin_countries_url }
      format.json { head :no_content }
    end
  end

  private

  def country_params
    params.require(:base_model_country).permit(:name, :code, :currency_code, :currency_symbol, :payment_provider, :tax, :language)
  end

  def sort_column
    BaseModel::Country.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/views/admin/countries/_form.html.haml
.form-container
  = simple_form_for @country, url: (@country.new_record? ? admin_countries_path() : admin_country_path(@country.id)), html: { class: 'form-content' } do |f|
    = f.error_notification
    = f.input :name, input_html: { maxlength: 32 }
    .split
      .split-element.size-20
        = f.input :code, wrapper_html: { class: 'split-element-content' }
      .split-element.size-30
        = f.input :currency_code, wrapper_html: { class: 'split-element-content' }
      .split-element.size-20
        = f.input :currency_symbol, wrapper_html: { class: 'split-element-content' }
      .split-element.size-30
        = f.input :tax, wrapper_html: { class: 'split-element-content' }
    = f.input :payment_provider, collection: BaseModel::Country.payment_provider_types, wrapper_html: { class: 'split-element-content' }, input_html: { class: 'select2' }
    .control-group
      .controls
        = f.button :submit, (@country.new_record? ? t('button.create') : t('button.update')), class: 'btn btn-inverse'

app/views/admin/countries/_menu.html.haml
.menu.navbar
  .navbar-inner
    %ul.nav
      %li{ class: ('active' if action?('index')) }= link_to t('admin.countries.link.countries'), admin_countries_path, class: 'nav-button'
      %li{ class: ('active' if action?('new', 'create')) }= link_to t('admin.countries.link.new_country'), new_admin_country_path, class: 'nav-button'
      - if defined?(buttons)
        - buttons.each do |button|
          %li= link_to t(button[:label]), button[:url], method: button[:method], confirm: button[:confirm].present? ? t(button[:confirm]) : nil, class: 'nav-button'

app/views/admin/countries/edit.html.haml
%h2= t 'admin.contries.header.edit_country'
= render partial: 'menu', locals: { buttons: [ { label: 'button.show_overview', url: admin_country_path(@country.id) },  { label: 'button.delete', url: admin_country_path(@country.id), method: :delete, confirm: 'label.confirm_delete' } ] }
= render partial: 'form'

app/views/admin/countries/index.html.haml
%h2= t 'admin.countries.header.admin_countries'
= render :partial => "menu"
#countries
  %table.table.table-hover.table-bordered.admin-index-table
    %tbody
      %tr
        %th.header= sortable 'name', t('admin.countries.label.name')
        %th.header= sortable 'tax', t('admin.countries.label.tax')
        %th.header= sortable 'payment_provider', t('admin.countries.label.payment_provider')
        %th
    - @countries.each do |country|
      %tr
        %td.title-column= link_to country.name, admin_country_path(country.id), class: 'title-link'
        %td.hint-column= country.tax.to_s
        %td.hint-column= country.payment_provider.humanize
        %td
          = link_to t('link.show'), admin_country_path(country.id), class: "btn btn-mini"
          = link_to t('link.edit'), edit_admin_country_path(country.id), class: "btn btn-mini"
          = link_to t('link.delete'), admin_country_path(country.id), method: :delete, data: { confirm: t('description.are_you_sure_question') }, class: "btn btn-mini btn-danger"
  = will_paginate @countries

app/views/admin/countries/new.html.haml
%h2= t 'admin.contries.header.new_country'
= render :partial => "menu"
= render :partial => "form"

app/views/admin/countries/show.html.haml
%h2= t 'admin.contries.header.show_country'
= render partial: 'menu', locals: { buttons: [ { label: 'button.edit', url: edit_admin_country_path(@country.id) },  { label: 'button.delete', url: admin_country_path(@country.id), method: :delete, confirm: 'label.confirm_delete' } ] }
.admin-show
  .split.admin-show-element
    .split-element.size-80
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.name'
          .admin-show-value= @country.name
    .split-element.size-20
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.country_code'
          .admin-show-value= @country.code
  .split.admin-show-element
    .split-element.size-40
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.payment_provider'
          .admin-show-value= @country.payment_provider_type
    .split-element.size-20
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.currency_code'
          .admin-show-value= @country.currency_code
    .split-element.size-20
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.currency_symbol'
          .admin-show-value= @country.currency_symbol
    .split-element.size-20
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.tax'
          .admin-show-value= @country.tax