config/routes.rb
Rails.application.routes.draw do

  # Root Homepage
  root                  to: 'public/pages#home'
  get '/:locale',       to: 'public/pages#home'

  # Local routes
  scope '/:locale' do

    resources :errors, only: [:show]

    namespace :admin do
      resources :users, :countries, :entries, :categories

      resources :courses do
        resources :lessons
      end

      # Attachments resource
      match '/attachments/:model/:id/:attachment/:return_url/(.:format)' => 'attachments#destroy', as: :attachment, via: [:delete, :get, :post]
    end

    scope module: 'public' do

      # Search resource aliases
      get     'search',                       to: 'searches#show'

      # Pages resource aliases
      get     '',                             to: 'pages#show', id: 'home'

      # Sessions resource aliases
      get     'login',                        to: 'sessions#new'
      post    'login',                        to: 'sessions#create'
      get     'logout',                       to: 'sessions#destroy'

      # User resource aliases
      get     'user/register',                to: 'users#new'
      post    'user/register',                to: 'users#create'
      get     'user/registered/:token',       to: 'users#created'
      get     'user/activate/:token',         to: 'users#activate'
      get     'user/activated/:token',        to: 'users#activated'
      get     'user/edit',                    to: 'users#edit'
      patch   'user/edit',                    to: 'users#update'
      get     'user/delete',                  to: 'users#delete'
      patch   'user/delete',                  to: 'users#activate_removal'
      get     'user/remove/:token',           to: 'users#destroy'
      get     'user/removed/:token',          to: 'users#removed'

      # Contact messages
      get     'contact',                      to: 'contact_messages#new'
      post    'contact',                      to: 'contact_messages#create'

      # Email change aliases
      get     'user/email-change',            to: 'email_changes#new'
      post    'user/email-change',            to: 'email_changes#create'
      get     'user/email-change/:token',     to: 'email_changes#update'

      # Password change aliases
      get     'user/password-change',         to: 'password_changes#edit'
      put     'user/password-change',         to: 'password_changes#update'

      # Password reset aliases
      get     'user/password-reset',          to: 'password_resets#new'
      post    'user/password-reset',          to: 'password_resets#create'
      get     'user/password-reset/:token',   to: 'password_resets#edit'
      put     'user/password-reset/:token',   to: 'password_resets#update'

      # Users resource
      resources :users do
        member do
          get 'created'             # Information page that activation email was sent.
          get 'activate'            # Activate user account.
          get 'activated'           # Welcome page for activated user.
          get 'delete'              # Form to remove account.
          patch 'activate_removal'  # Sent an email message with confirmation link for removal process.
          get 'removed'             # Message that account had been removed.
        end

        # Password Change resource
        resource :password_change,  only: [:edit, :update]

        # Email Change resource
        resource :email_change,  only: [:new, :create, :update]
      end

      # Password reset resource
      resources :password_resets, only: [:new, :create, :edit, :update] do
        collection do
          get 'created'
        end
      end

      # Pages resource
      resources :pages, only: [:show]

      # Contact messages resource
      resources :contact_messages,     only: [:new, :create]

      # Entries resource
      resources :entries,     only: [:show]

      # Categories resource
      # resources :categories,  only: [ :show ]

      # Search resource
      resource :searches,    only: [:show]

      # Sessions resource
      resource  :sessions,    only: [:new, :create, :destroy]

      # Dashboard resource
      resource  :dashboard,   only: [:show]

    end

  end

  # mount Ckeditor::Engine => '/ckeditor'
end

app/models/base_model/entry.rb
class BaseModel::Entry < ActiveRecord::Base
  self.table_name = 'entry'
  self.per_page = 20

  belongs_to :country
  belongs_to :user

  as_enum :status_type,             { error: 0, disabled: 1, enabled: 2, pinned: 4 }, source: 'status'
  as_enum :main_display_mode_type,  { hide: 0, small: 1, medium: 2, large: 4 }, source: 'main_display_mode'

  scope :disabled,          -> { where(status: self.status_types[:disabled] ) }
  scope :enabled,           -> { where(status: self.status_types[:enabled] ) }
  scope :pinned,            -> { where(status: self.status_types[:pinned] ) }
  scope :public_accessible, -> { where(status: [ self.status_types[:enabled], self.status_types[:pinned] ] ) }
  scope :display_available, -> { where(main_display_mode: [ self.main_display_mode_types[:small], self.main_display_mode_types[:medium], self.main_display_mode_types[:large] ]) }
  scope :language,          ->(country_code) { where('country.code = ?', country_code).joins(:country) }
  scope :search,            ->(keywords) { where('entry.title LIKE :keywords OR entry.short_text LIKE :keywords', keywords: "%#{keywords}%") }

  has_attached_file :image, styles: {
      large:    [ '1200x300#', :jpg, ],
      medium:   [ '580x296#', :jpg, ],
      small:    [ '285x194#', :jpg, ],
      thumb:    [ '200x120>', :jpg, ]
  },
  convert_options: {
      large:    '-resize 1200x300^ -gravity center -crop 1200x300+0+0 -quality 80',
      medium:   '-quality 80',
      small:    '-quality 80'
  }

  has_attached_file :banner, styles: {
      regular:  [ '1200x150#', :jpg ],
      thumb:    [ '200x120>', :jpg ]
  },
  convert_options: {
      regular: '-resize 1200x150^ -gravity center -crop 1200x150+0+0 -quality 80'
  }

  validates :text,              presence:     true,
                                length:       100..100000
  validates :short_text,        presence:     true,
                                length:       50..10000
  validates :code,              allow_blank:  true,
                                length:       100..10000
  validates :title,             presence:     true,
                                length:       5..128
  validates :status,            presence:     true
  validates :main_display_mode, presence:     true
  validates :hits,              numericality: { only_integer: true }
  validates :country,           presence:     true,
                                existence:    true
  validates :user,              presence:     true,
                                existence:    true

  validates :image,             attachment_size: 0..5.megabytes,
                                attachment_content_type: { content_type: ['image/jpeg', 'image/png'], message: 'form.error.file_type' }
  validates :banner,            attachment_size: 0..5.megabytes,
                                attachment_content_type: { content_type: ['image/jpeg', 'image/png'], message: 'form.error.file_type' }

  after_initialize :init

  def init
    if self.new_record?
      self.main_display_mode = BaseModel::Entry.main_display_mode_types.small
      self.hits = 0
      self.status ||= BaseModel::Entry.status_types.disabled
    end
  end
end

app/controllers/admin/entries_controller.rb
class Admin::EntriesController < Admin::AdminController
  helper_method :sort_column, :sort_direction

  # GET /admin/entries
  # GET /admin/entries.json
  def index
    @entries = BaseModel::Entry.paginate(page: params[:page]).order(sort_column + " " + sort_direction).includes(:country)

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @entries }
    end
  end

  # GET /admin/entries/1
  # GET /admin/entries/1.json
  def show
    @entry = BaseModel::Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /admin/entries/new
  # GET /admin/entries/new.json
  def new
    @entry = BaseModel::Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /admin/entries/1/edit
  def edit
    @entry = BaseModel::Entry.find(params[:id])
  end

  # POST /admin/entries
  # POST /admin/entries.json
  def create
    @entry = BaseModel::Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to admin_entry_path(@entry), notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/entries/1
  # PUT /admin/entries/1.json
  def update
    @entry = BaseModel::Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(entry_params)
        format.html { redirect_to edit_admin_entry_path(@entry.id), notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/entries/1
  # DELETE /admin/entries/1.json
  def destroy
    @entry = BaseModel::Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to admin_entries_url }
      format.json { head :no_content }
    end
  end

  private

  def entry_params
    params.require(:base_model_entry).permit(:user_id, :country_id, :status, :main_display_mode, :text, :short_text, :code, :title, :image, :banner)
  end

  def sort_column
    BaseModel::Entry.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/views/admin/entries/_form.html.haml
.form-container
  = simple_form_for @entry, url: (@entry.new_record? ? admin_entries_path() : admin_entry_path(@entry.id)), html: { multipart: true, class: 'form-content' } do |f|
    = f.error_notification
    = f.input :title, input_html: { maxlength: 128 }
    = f.input :short_text, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' }, maxlength: 100000, value: @entry.short_text }
    = f.input :text, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' }, maxlength: 100000, value: @entry.text }
    = f.input :code, input_html: { maxlength: 10000 }
    = file_field_for(f, :image, :thumb)
    = file_field_for(f, :banner, :thumb)
    .split
      .split-element.size-30
        = f.input :main_display_mode, collection: BaseModel::Entry.main_display_mode_types, wrapper_html: { class: 'split-element-content' }, input_html: { class: 'select2' }
      .split-element.size-30
        = f.input :status, collection: BaseModel::Entry.status_types, wrapper_html: { class: 'split-element-content' }, input_html: { class: 'select2' }
      .split-element.size-40
        = f.association :country, wrapper_html: { class: 'split-element-content' }, input_html: { class: 'select2' }

    = f.association :user, label_method: :email, input_html: { class: 'select2' }
    .control-group
      .controls
        = f.button :submit, (@entry.new_record? ? t('button.create') : t('button.update')), class: 'btn btn-inverse'

app/views/admin/entries/_menu.html.haml
.menu.navbar
  .navbar-inner
    %ul.nav
      %li{ class: ('active' if action?('index')) }= link_to t('admin.countries.link.entries'), admin_entries_path, class: 'nav-button'
      %li{ class: ('active' if action?('new', 'create')) }= link_to t('admin.countries.link.new_entry'), new_admin_entry_path, class: 'nav-button'
      - if defined?(buttons)
        - buttons.each do |button|
          %li= link_to t(button[:label]), button[:url], method: button[:method], confirm: button[:confirm].present? ? t(button[:confirm]) : nil, class: 'nav-button'

app/views/admin/entries/edit.html.haml
%h2= t 'admin.entries.header.edit_entry'
= render partial: 'menu', locals: { buttons: [ { label: 'button.show_public', url: entry_path(@entry.id) }, { label: 'button.show_overview', url: admin_entry_path(@entry.id) },  { label: 'button.delete', url: admin_entry_path(@entry.id), method: :delete, confirm: 'label.confirm_delete' } ] }
= render partial: 'form'

app/views/admin/entries/index.html.haml
%h2= t 'admin.entries.header.admin_entries'
= render :partial => "menu"
#entries
  %table.table.table-hover.table-bordered.admin-index-table
    %tbody
      %tr
        %th= sortable 'title', t('admin.entries.label.title')
        %th.header= sortable 'country', t('admin.entries.label.country')
        %th.header= sortable 'status', t('admin.entries.label.status')
        %th.header= sortable 'hits', t('admin.entries.label.hits')
        %th
    - @entries.each do |entry|
      %tr
        %td.title-column
          .image-thumb
            = link_to(image_tag(entry.image.url(:thumb)), entry_path(entry.id))
          = link_to entry.title, entry_path(entry.id), class: 'title-link'
        %td.hint-column= entry.country.name
        %td.hint-column= entry.status_type.to_s
        %td.hint-column= entry.hits
        %td.options-column
          = link_to t('link.show'), admin_entry_path(entry.id), class: "btn btn-mini"
          = link_to t('link.edit'), edit_admin_entry_path(entry.id), class: "btn btn-mini"
          = link_to t('link.delete'), admin_entry_path(entry.id), method: :delete, data: { confirm: t('description.are_you_sure_question') }, class: "btn btn-mini btn-danger"
  = will_paginate @entries

app/views/admin/entries/new.html.haml
%h2= t 'admin.entries.header.new_entry'
= render :partial => "menu"
= render :partial => "form"

app/views/admin/entries/show.html.haml
%h2= t 'admin.entries.header.show_entry'
= render partial: 'menu', locals: { buttons: [ { label: 'button.show_public', url: entry_path(@entry.id) }, { label: 'button.edit', url: edit_admin_entry_path(@entry.id) },  { label: 'button.delete', url: admin_entry_path(@entry.id), method: :delete, confirm: 'label.confirm_delete' } ] }
.admin-show
  .admin-show-input.admin-show-element
    .admin-show-label= t 'label.title'
    .admin-show-value= @entry.title
  .admin-show-text.admin-show-element
    .admin-show-label= t 'label.text'
    .admin-show-value= @entry.text.html_safe
  .admin-show-text.admin-show-element
    .admin-show-label= t 'label.short_text'
    .admin-show-value= @entry.short_text.html_safe
  .admin-show-text.admin-show-element
    .admin-show-label= t 'label.code'
    .admin-show-value= @entry.code
  .admin-show-input.admin-show-element
    .admin-show-label= t 'label.user'
    .admin-show-value= link_to @entry.user.full_name_with_email, admin_user_path(@entry.user)
  .split.admin-show-element
    .split-element.size-50
      .split-element-content
        .admin-show-image
          .admin-show-label= t 'label.image'
          .admin-show-value= image_tag @entry.image.url(:thumb), class: 'img-polaroid'
    .split-element.size-50
      .split-element-content
        .admin-show-image
          .admin-show-label= t 'label.banner'
          .admin-show-value= image_tag @entry.banner.url(:thumb), class: 'img-polaroid'
  .split.admin-show-element
    .split-element.size-20
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.status'
          .admin-show-value= @entry.status_type
    .split-element.size-30
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.main_display_mode'
          .admin-show-value= @entry.main_display_mode_type
    .split-element.size-20
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.hits'
          .admin-show-value= @entry.hits
    .split-element.size-30
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.country'
          .admin-show-value= link_to @entry.country.name, admin_country_path(@entry.country)
  .split.admin-show-element
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.created_at'
          .admin-show-value= @entry.updated_at
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.updated_at'
          .admin-show-value= @entry.created_at