config/routes.rb
Rails.application.routes.draw do

  # Root Homepage
  root                  to: 'public/pages#home'
  get '/:locale',       to: 'public/pages#home'

  # Local routes
  scope '/:locale' do

    resources :errors, only: [:show]

    namespace :admin do
      resources :users, :countries, :entries, :categories

      resources :courses do
        resources :lessons
      end

      # Attachments resource
      match '/attachments/:model/:id/:attachment/:return_url/(.:format)' => 'attachments#destroy', as: :attachment, via: [:delete, :get, :post]
    end

    scope module: 'public' do

      # Search resource aliases
      get     'search',                       to: 'searches#show'

      # Pages resource aliases
      get     '',                             to: 'pages#show', id: 'home'

      # Sessions resource aliases
      get     'login',                        to: 'sessions#new'
      post    'login',                        to: 'sessions#create'
      get     'logout',                       to: 'sessions#destroy'

      # User resource aliases
      get     'user/register',                to: 'users#new'
      post    'user/register',                to: 'users#create'
      get     'user/registered/:token',       to: 'users#created'
      get     'user/activate/:token',         to: 'users#activate'
      get     'user/activated/:token',        to: 'users#activated'
      get     'user/edit',                    to: 'users#edit'
      patch   'user/edit',                    to: 'users#update'
      get     'user/delete',                  to: 'users#delete'
      patch   'user/delete',                  to: 'users#activate_removal'
      get     'user/remove/:token',           to: 'users#destroy'
      get     'user/removed/:token',          to: 'users#removed'

      # Contact messages
      get     'contact',                      to: 'contact_messages#new'
      post    'contact',                      to: 'contact_messages#create'

      # Email change aliases
      get     'user/email-change',            to: 'email_changes#new'
      post    'user/email-change',            to: 'email_changes#create'
      get     'user/email-change/:token',     to: 'email_changes#update'

      # Password change aliases
      get     'user/password-change',         to: 'password_changes#edit'
      put     'user/password-change',         to: 'password_changes#update'

      # Password reset aliases
      get     'user/password-reset',          to: 'password_resets#new'
      post    'user/password-reset',          to: 'password_resets#create'
      get     'user/password-reset/:token',   to: 'password_resets#edit'
      put     'user/password-reset/:token',   to: 'password_resets#update'

      # Users resource
      resources :users do
        member do
          get 'created'             # Information page that activation email was sent.
          get 'activate'            # Activate user account.
          get 'activated'           # Welcome page for activated user.
          get 'delete'              # Form to remove account.
          patch 'activate_removal'  # Sent an email message with confirmation link for removal process.
          get 'removed'             # Message that account had been removed.
        end

        # Password Change resource
        resource :password_change,  only: [:edit, :update]

        # Email Change resource
        resource :email_change,  only: [:new, :create, :update]
      end

      # Password reset resource
      resources :password_resets, only: [:new, :create, :edit, :update] do
        collection do
          get 'created'
        end
      end

      # Pages resource
      resources :pages, only: [:show]

      # Contact messages resource
      resources :contact_messages,     only: [:new, :create]

      # Entries resource
      resources :entries,     only: [:show]

      # Categories resource
      # resources :categories,  only: [ :show ]

      # Search resource
      resource :searches,    only: [:show]

      # Sessions resource
      resource  :sessions,    only: [:new, :create, :destroy]

      # Dashboard resource
      resource  :dashboard,   only: [:show]

    end

  end

  # mount Ckeditor::Engine => '/ckeditor'
end

app/models/base_model/user.rb
class BaseModel::User < ActiveRecord::Base
  AuthenticationError = Class.new(StandardError)
  AuthorizationError = Class.new(StandardError)

  self.table_name = 'user'

  authenticates_with_sorcery!
  simple_roles

  attr_accessor :password, :password_confirmation, :terms_of_service, :captcha

  has_many :entries

  scope :editors,       -> { where( role: :editor) }
  scope :admins,        -> { where( role: :admin) }
  scope :baned,         -> { where( status_type: :baned ) }
  scope :disabled,      -> { where( status_type: :disabled ) }
  scope :enabled,       -> { where( status_type: :enabled ) }
  scope :males,         -> { where( gender_type: :male ) }
  scope :females,       -> { where( gender_type: :female ) }
  scope :country_code,  ->(code) { where(country_id: code ) }

  as_enum :gender_type,  { male: 'M', female: 'F' }, source: 'gender'
  as_enum :status_type,  { removed: 0, baned: 1, disabled: 2, enabled: 3 }, source: 'status'

  validates :provider,              length:       1..100,
                                    allow_blank:  true
  validates :provider_id,           length:       1..100,
                                    allow_blank:  true
  validates :first_name,            length:       2..30,
                                    allow_blank:  true
  validates :last_name,             length:       2..30,
                                    allow_blank:  true
  validates :website,               url:          true,
                                    length:       10..100,
                                    allow_blank:  true
  validates :phone_number,          length:       4..20,
                                    allow_blank:  true
  validates :email,                 presence:     true,
                                    email:        true,
                                    length:       { maximum: 80 },
                                    uniqueness:   { case_sensitive: false }
  validates :password,              presence:     true,
                                    length:       { minimum: 6 },
                                    on:           :create
  validates :role,                  inclusion:    { in: SimpleRoles.config.valid_roles }
  validates :address,               length:       2..100,
                                    allow_blank:  true
  validates :location,              length:       2..100,
                                    allow_blank:  true
  validates :zip_code,              length:       2..10,
                                    allow_blank:  true
  validates :country_id,            inclusion:    { in: Country.all.to_a.map { |country| country[1] } },
                                    allow_blank:  true
  validates :status,                inclusion:    { in: status_types.values_at(:removed, :baned, :disabled, :enabled) }
  validates :gender,                presence:     true
  validates :birth_date,            presence:     true,
                                    date:         {
                                        after: Proc.new { Time.now - 100.years },
                                        before: Proc.new { Time.now - 6.year }
                                    }

  # Public validators
  validates :password,              confirmation: true,
                                    on:           :create,
                                    if:           :user_registration?
  validates :password_confirmation, presence:     true,
                                    on:           :create,
                                    if:           :user_registration?
  validates :terms_of_service,      acceptance:   '1',
                                    on:           :create,
                                    if:           :user_registration?

  before_create :generate_identification_token
  after_initialize :init

  def user_registration?
    # TODO method to check if action is registration to make extra validation work
    false
  end

  def new_email=(email)
    encryptor = ActiveSupport::MessageEncryptor.new(Digest::SHA1.hexdigest(self.salt))
    self.encrypted_new_email = encryptor.encrypt_and_sign(email)
  end

  def new_email
    encryptor = ActiveSupport::MessageEncryptor.new(Digest::SHA1.hexdigest(self.salt))
    encryptor.decrypt_and_verify(self.encrypted_new_email)
  end

  # Callback "before_create"
  # Set the default attributes.
  def generate_identification_token
    self.identification_token = Digest::MD5.hexdigest(Time.now.to_s+'23hgu23jv24')
  end

  def generate_removal_token
    self.removal_token = Digest::MD5.hexdigest(Time.now.to_s+'1d234rds2ji')
  end

  def deliver_removal_instructions
    self.generate_removal_token
    self.save && UserMailer.account_removal_email(self).deliver
  end

  def remove
    self.status = BaseModel::User.status_types[:removed]
    self.email = nil
    self.removal_token = nil
    self.save!(validate: false)
  end

  def reset_password(password)
    self.password_confirmation = password
    self.change_password!(password)
  end

  def reset_email(email)
    self.email = email
    self.encrypted_new_email = nil
    self.save!
  end

  def able_to_logged_in?
    [:enabled].include? self.status_type
  end

  def full_name
    if first_name.present? || last_name.present?
      (first_name.to_s+' '+last_name.to_s).strip
    end
  end

  def full_name_or_email
    if first_name.present? || last_name.present?
      (first_name.to_s+' '+last_name.to_s).strip
    else
      email
    end
  end

  def full_name_with_email
    (first_name+' '+last_name+' ('+email+')').strip
  end

  def website_name
    if website
      URI.parse(website).host
    end
  end

  def self.load_from_encrypted_new_email(encrypted_email)
    return nil if encrypted_email.blank?
    user = find_by_encrypted_new_email(encrypted_email)
    return user.blank? ? nil : user
  end

  def self.load_from_removal_token(token)
    return nil if token.blank?
    user = find_by_removal_token(token)
    return user.blank? ? nil : user
  end

  def self.load_from_identification_token(token)
    return nil if token.blank?
    user = find_by_identification_token(token)
    return user.blank? ? nil : user
  end

  def admin_update_attributes(attributes)
    if self.valid?
      if (attributes.include?(:password))
        self.reset_password(attributes[:password])
        attributes.delete(:password)
      end
      self.update_attributes(attributes)
    end
  end

  # Update user settings
  def update_settings!(params)
    self.update_attributes({
      first_name: params[:first_name],
      last_name: params[:last_name],
      website: params[:website],
      phone_number: params[:phone_number],
      address: params[:address],
      zip_code: params[:zip_code],
      location: params[:location],
      country_id: params[:country_id],
    })
  end

  # Activate user account
  def activate!
    self.generate_identification_token
    self.status = BaseModel::User.status_types[:enabled]
    super
  end

  private

  # Callback "before_validate"
  # Set the default attributes.
  def init
    if self.new_record?
      self.status ||= BaseModel::User.status_types[:disabled]
      self.role ||= :user
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  helper_method :sort_column, :sort_direction

  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = BaseModel::User.paginate(page: params[:page]).order(sort_column + " " + sort_direction)

    @countries = Country.all.to_a.map { |country| country[1] }
    p @countries.inspect


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    @user = BaseModel::User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    @user = BaseModel::User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @user = BaseModel::User.find(params[:id])
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = BaseModel::User.new(params[:admin_user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @user = BaseModel::User.find(params[:id])

    respond_to do |format|
      if @user.admin_update_attributes(params[:admin_user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user = BaseModel::User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    BaseModel::User.column_names.include?(params[:sort]) ? params[:sort] : 'id'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end
end

app/views/admin/users/_form.html.haml
.form-container
  = simple_form_for @user, :url => (@user.new_record? ? admin_users_path() : admin_user_path(@user.id)), :html => {:class => 'form-content' } do |f|
    = f.error_notification
    .form-separator= t 'form.label.personal_data'
    = f.input :email, :wrapper_html => { :class => 'split-element-content' }
    .split
      .split-element.size-50
        = f.input :first_name, :wrapper_html => { :class => 'split-element-content' }
      .split-element.size-50
        = f.input :gender, :collection => [[t('common.male'), 'M'], [t('common.female'), 'F']], :as => :select, :item_wrapper_class => 'inline'
    .split
      .split-element.size-50
        = f.input :last_name, :wrapper_html => { :class => 'split-element-content' }
      .split-element.size-50
        = f.input :birth_date, :as => :date, :start_year => Date.today.year - 90, :end_year => Date.today.year - 7, :order => [:day, :month, :year], :required => true, :wrapper_html => { :class => 'split-element-content date-select-group' }

    .form-separator= t 'form.label.address_data'
    .split
      .split-element.size-50
        = f.input :country_id, collection: Country.all, wrapper_html: { :class => 'split-element-content' }
      .split-element.size-50
        = f.input :address, :wrapper_html => { :class => 'split-element-content' }
    .split
      .split-element.size-50
        = f.input :location, :wrapper_html => { :class => 'split-element-content' }
      .split-element.size-50
        = f.input :zip_code, :wrapper_html => { :class => 'split-element-content' }

    .form-separator= t 'form.label.contact_data'
    = f.input :email, :wrapper_html => { :class => 'split-element-content' }
    .split
      .split-element.size-50
        = f.input :website, :wrapper_html => { :class => 'split-element-content' }
      .split-element.size-50
        = f.input :phone_number, :wrapper_html => { :class => 'split-element-content' }

    .form-separator= t 'form.label.other_data'
    .split
      .split-element.size-50
        = f.input :status, :collection => BaseModel::User.status_types, :wrapper_html => { :class => 'split-element-content' }
      .split-element.size-50
        = f.input :role, :collection => SimpleRoles.config.valid_roles, :wrapper_html => { :class => 'split-element-content' }
    = f.input :password, :wrapper_html => { :class => 'split-element-content' }

    .control-group
      .controls
        = f.button :submit, (@user.new_record? ? t('button.create') : t('button.update')), :class => 'btn btn-inverse'

app/views/admin/users/_menu.html.haml
.menu.navbar
  .navbar-inner
    %ul.nav
      %li{ class: ('active' if action?('index')) }= link_to t('admin.countries.link.users'), admin_users_path, class: 'nav-button'
      %li{ class: ('active' if action?('new', 'create')) }= link_to t('admin.countries.link.new_user'), new_admin_user_path, class: 'nav-button'
      - if defined?(buttons)
        - buttons.each do |button|
          %li= link_to t(button[:label]), button[:url], method: button[:method], confirm: button[:confirm].present? ? t(button[:confirm]) : nil, class: 'nav-button'

app/views/admin/users/edit.html.haml
%h2= t 'admin.users.header.edit_user'
= render partial: 'menu', locals: { buttons: [ { label: 'button.show_overview', url: admin_user_path(@user.id) },  { label: 'button.delete', url: admin_user_path(@user.id), method: :delete, confirm: 'label.confirm_delete' } ] }
= render partial: 'form'

app/views/admin/users/index.html.haml
%h2= t 'admin.users.header.admin_users'
= render partial: 'menu'
#users
  %table.table.table-hover.table-bordered.admin-index-table
    %tbody
      %tr
        %th.header= sortable 'email', t('admin.users.label.email')
        %th.header= sortable 'last_name', t('admin.users.label.full_name')
        %th.header= sortable 'status',  t('admin.users.label.status')
        %th
    - @users.each do |user|
      %tr
        %td= link_to user.email, admin_user_path(user.id), class: 'title-link'
        %td= link_to user.full_name_or_email, admin_user_path(user.id), class: 'title-link'
        %td.hint-column= user.status_type
        %td.options-column
          = link_to t('link.show'), admin_user_path(user.id), class: "btn btn-mini"
          = link_to t('link.edit'), edit_admin_user_path(user.id), class: "btn btn-mini"
          = link_to t('link.delete'), admin_user_path(user.id), method: :delete, data: { confirm: t('description.are_you_sure_question') }, class: "btn btn-mini btn-danger"
  = will_paginate @users

app/views/admin/users/new.html.haml
%h2= t 'admin.users.header.new_user'
= render :partial => "menu"
= render :partial => "form"

app/views/admin/users/show.html.haml
%h2= t 'admin.users.header.show_user'
= render partial: 'menu', locals: { buttons: [ { label: 'button.edit', url: edit_admin_user_path(@user.id) },  { label: 'button.delete', url: admin_user_path(@user.id), method: :delete, confirm: 'label.confirm_delete' } ] }
.admin-show
  .data-separator= t 'label.personal_data'
  .split.admin-show-element
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.first_name'
          .admin-show-value= @user.first_name
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.last_name'
          .admin-show-value= @user.last_name
  .split.admin-show-element
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.gender'
          .admin-show-value= @user.gender_type
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.birth_date'
          .admin-show-value= @user.birth_date

  .data-separator= t 'label.contact_data'
  .admin-show-input.admin-show-element
    .admin-show-label= t 'label.email'
    .admin-show-value= @user.email
  .split.admin-show-element
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.website'
          .admin-show-value= @user.website
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.phone_number'
          .admin-show-value= @user.phone_number

  .data-separator= t 'label.address_data'
  .split.admin-show-element
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.country_id'
          .admin-show-value= @user.country_id
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.address'
          .admin-show-value= @user.address
  .split.admin-show-element
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.location'
          .admin-show-value= @user.location
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.zip_code'
          .admin-show-value= @user.zip_code
  .data-separator= t 'label.other_data'
  .split.admin-show-element
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.status'
          .admin-show-value= @user.status_type
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.role'
          .admin-show-value= @user.role
  .admin-show-input.admin-show-element
    .admin-show-label= t 'label.identification_token'
    .admin-show-value= @user.identification_token
  - if @user.activation_token
    .admin-show-input.admin-show-element
      .admin-show-label
        = t 'label.activation_link'
        = link_to t('button.activate'), { controller: 'public/users', action: 'activate', token: @user.activation_token, locale: I18n.locale, only_path: false }, class: 'btn btn-primary btn-small pull-right'
      .admin-show-value= url_for controller: 'public/users', action: 'activate', token: @user.activation_token, locale: I18n.locale, only_path: false
  - if @user.removal_token
    .admin-show-input.admin-show-element
      .admin-show-label
        = t 'label.activation_link'
        = link_to t('button.remove'), { controller: 'public/users', action: 'destroy', token: @user.removal_token, locale: I18n.locale, only_path: false }, class: 'btn btn-danger btn-small pull-right'
      .admin-show-value= url_for controller: 'public/users', action: 'destroy', token: @user.removal_token, locale: I18n.locale, only_path: false
  .split.admin-show-element
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.external_provider'
          .admin-show-value= @user.provider
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.external_provider_id'
          .admin-show-value= @user.provider_id
  .split.admin-show-element
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.created_at'
          .admin-show-value= @user.updated_at
    .split-element.size-50
      .split-element-content
        .admin-show-input
          .admin-show-label= t 'label.updated_at'
          .admin-show-value= @user.created_at