config/routes.rb
Rails.application.routes.draw do

  # Root Homepage
  root                  to: 'public/pages#home'
  get '/:locale',       to: 'public/pages#home'

  # Local routes
  scope '/:locale' do

    resources :errors, only: [:show]

    namespace :admin do
      resources :users, :countries, :entries, :categories

      resources :courses do
        resources :lessons
      end

      # Attachments resource
      match '/attachments/:model/:id/:attachment/:return_url/(.:format)' => 'attachments#destroy', as: :attachment, via: [:delete, :get, :post]
    end

    scope module: 'public' do

      # Search resource aliases
      get     'search',                       to: 'searches#show'

      # Pages resource aliases
      get     '',                             to: 'pages#show', id: 'home'

      # Sessions resource aliases
      get     'login',                        to: 'sessions#new'
      post    'login',                        to: 'sessions#create'
      get     'logout',                       to: 'sessions#destroy'

      # User resource aliases
      get     'user/register',                to: 'users#new'
      post    'user/register',                to: 'users#create'
      get     'user/registered/:token',       to: 'users#created'
      get     'user/activate/:token',         to: 'users#activate'
      get     'user/activated/:token',        to: 'users#activated'
      get     'user/edit',                    to: 'users#edit'
      patch   'user/edit',                    to: 'users#update'
      get     'user/delete',                  to: 'users#delete'
      patch   'user/delete',                  to: 'users#activate_removal'
      get     'user/remove/:token',           to: 'users#destroy'
      get     'user/removed/:token',          to: 'users#removed'

      # Contact messages
      get     'contact',                      to: 'contact_messages#new'
      post    'contact',                      to: 'contact_messages#create'

      # Email change aliases
      get     'user/email-change',            to: 'email_changes#new'
      post    'user/email-change',            to: 'email_changes#create'
      get     'user/email-change/:token',     to: 'email_changes#update'

      # Password change aliases
      get     'user/password-change',         to: 'password_changes#edit'
      put     'user/password-change',         to: 'password_changes#update'

      # Password reset aliases
      get     'user/password-reset',          to: 'password_resets#new'
      post    'user/password-reset',          to: 'password_resets#create'
      get     'user/password-reset/:token',   to: 'password_resets#edit'
      put     'user/password-reset/:token',   to: 'password_resets#update'

      # Users resource
      resources :users do
        member do
          get 'created'             # Information page that activation email was sent.
          get 'activate'            # Activate user account.
          get 'activated'           # Welcome page for activated user.
          get 'delete'              # Form to remove account.
          patch 'activate_removal'  # Sent an email message with confirmation link for removal process.
          get 'removed'             # Message that account had been removed.
        end

        # Password Change resource
        resource :password_change,  only: [:edit, :update]

        # Email Change resource
        resource :email_change,  only: [:new, :create, :update]
      end

      # Password reset resource
      resources :password_resets, only: [:new, :create, :edit, :update] do
        collection do
          get 'created'
        end
      end

      # Pages resource
      resources :pages, only: [:show]

      # Contact messages resource
      resources :contact_messages,     only: [:new, :create]

      # Entries resource
      resources :entries,     only: [:show]

      # Categories resource
      # resources :categories,  only: [ :show ]

      # Search resource
      resource :searches,    only: [:show]

      # Sessions resource
      resource  :sessions,    only: [:new, :create, :destroy]

      # Dashboard resource
      resource  :dashboard,   only: [:show]

    end

  end

  # mount Ckeditor::Engine => '/ckeditor'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TODO
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js'
    -#= javascript_include_tag 'plugins/jquery.nested.js'
    - if current_user && current_user.is_admin?
      = javascript_include_tag 'ckeditor/init'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    #main
      %header
        .container-fluid
          .row
            .col-xs-4
              #logo
            .col-xs-8
              %nav
      #content
        .container-fluid
          = render(partial: 'shared/notice_messages')
          = content_for?(:content) ? yield(:content) : yield
      %footer
        .container-fluid
          .row

-# Extra JavaScript from different templates
= yield(:script)

app/views/layouts/dashboard.html.haml
- content_for :content do
  .row
    .span3
      .well.dashboard-nav
        %ul.nav.nav-list
          %li.nav-header= t 'label.manage_profile'
          %li= link_to t('label.dashboard'), '#'
          %li= link_to t('label.my_courses'), '#'
          %li= link_to t('label.settings'),             controller: 'public/users', action: 'edit'
          - if current_user.is_admin?
            %li.nav-header= t 'label.manage_site'
            %li= link_to t('label.manage_courses'), admin_courses_path
            %li= link_to t('label.manage_entries'), admin_entries_path
            %li= link_to t('label.manage_users'), admin_users_path
            %li= link_to t('label.manage_categories'), admin_categories_path
            %li= link_to t('label.manage_countries'), admin_countries_path
            %li= link_to t('label.payments'), '#'
          %li.divider
          %li= link_to t('label.change_password'),      controller: 'public/password_changes', action: 'edit'
          %li= link_to t('label.change_email'),         controller: 'public/email_changes', action: 'new'
          %li= link_to t('label.delete_account'),       controller: 'public/users', action: 'delete'

    .span9
      = content_for?(:dashboard_content) ? yield(:dashboard_content) : yield
= render template: 'layouts/application'

app/views/layouts/email.html.haml
.email-body{ style: 'color: black;' }
  .email-header{ style: 'border-bottom: 7px solid black;color:#d70d00;' }
    %h1= APP_CONFIG['website_name']
  .email-conteiner{ style: 'padding:10px 0px 20px 0px;border-bottom: 1px dotted black;text-align: justify;font-size: 1pc; line-height: 1.4pc;margin-bottom:10px;' }
    = yield
  .email-footer
    .email-footer-address{ style: 'padding:0px 10px 0px 0px;width:210px;float:left;border-right: 1px dotted black;' }
      = APP_CONFIG['address']['name']
      %br
      = APP_CONFIG['address']['street']
      %br
      = "#{APP_CONFIG['address']['zip_code']} #{APP_CONFIG['address']['city']}"
    .email-footer-information{ style: 'padding:0px 10px;float:left;' }
      = APP_CONFIG['contact']['phone']
      %br
      = APP_CONFIG['contact']['email']